/**
 * Which record fields the engine rolls, and the order it draws them in.
 *
 * An item's stats are not stored in a save: the save carries a seed, and the
 * engine walks a fixed list of fields drawing one value per field from a single
 * stream. Get the list or its order wrong and every field after the mistake
 * comes out wrong, so this table is the whole contract.
 *
 * The field membership and ordering were established by reading the reference
 * SDK at marius00/GrimDawnItemStats, commit
 * 97927f261a489553f79d541ad9f83cf6caa64c81 (javascript-sdk/src/engine.js,
 * sha256 02daa300dfe10a9855877dddf7e07f8e48af823853189f832703fa437173c155),
 * and re-verified against a live character's item tooltips. The arithmetic and
 * traversal here are ours; nothing is copied from it and nothing reads it at
 * runtime.
 */

/** How a kind consumes the stream, which decides how many draws a field costs. */
export type RollKind =
  | 'Char'
  | 'Flat'
  | 'SlowFlat'
  | 'Dmg'
  | 'Leech'
  | 'OffReflex'
  | 'OffSlow'
  | 'OffReduc'
  | 'RetalFlat'
  | 'RetalDur'
  | 'RetalMod'
  | 'RetalReflex'
  | 'Def'
  | 'Conv'
  | 'Skill';

/** Every rollable field, in the order the engine draws them. */
export const ROLL_ORDER: readonly { readonly kind: RollKind; readonly field: string }[] = [
  // Char: 33 fields
  { kind: 'Char', field: 'characterStrength' },
  { kind: 'Char', field: 'characterDexterity' },
  { kind: 'Char', field: 'characterIntelligence' },
  { kind: 'Char', field: 'characterLife' },
  { kind: 'Char', field: 'characterMana' },
  { kind: 'Char', field: 'characterStrengthModifier' },
  { kind: 'Char', field: 'characterDexterityModifier' },
  { kind: 'Char', field: 'characterIntelligenceModifier' },
  { kind: 'Char', field: 'characterLifeModifier' },
  { kind: 'Char', field: 'characterManaModifier' },
  { kind: 'Char', field: 'characterLifeMultModifier' },
  { kind: 'Char', field: 'characterOffensiveAbility' },
  { kind: 'Char', field: 'characterDefensiveAbility' },
  { kind: 'Char', field: 'characterOffensiveAbilityModifier' },
  { kind: 'Char', field: 'characterDefensiveAbilityModifier' },
  { kind: 'Char', field: 'characterLifeRegen' },
  { kind: 'Char', field: 'characterLifeRegenModifier' },
  { kind: 'Char', field: 'characterManaRegenModifier' },
  { kind: 'Char', field: 'characterConstitutionModifier' },
  { kind: 'Char', field: 'characterHealIncreasePercent' },
  { kind: 'Char', field: 'characterTotalSpeedModifier' },
  { kind: 'Char', field: 'characterAttackSpeedModifier' },
  { kind: 'Char', field: 'characterAttackSpeedMaxModifier' },
  { kind: 'Char', field: 'characterSpellCastSpeedModifier' },
  { kind: 'Char', field: 'characterSpellCastSpeedMaxModifier' },
  { kind: 'Char', field: 'characterRunSpeedModifier' },
  { kind: 'Char', field: 'characterRunSpeedMaxModifier' },
  { kind: 'Char', field: 'characterDefensiveBlockRecoveryReduction' },
  { kind: 'Char', field: 'characterEnergyAbsorptionPercent' },
  { kind: 'Char', field: 'characterDodgePercent' },
  { kind: 'Char', field: 'characterDeflectProjectile' },
  { kind: 'Char', field: 'characterManaLimitReserve' },
  { kind: 'Char', field: 'characterManaLimitReserveModifier' },
  // Flat: 11 fields
  { kind: 'Flat', field: 'offensivePhysical' },
  { kind: 'Flat', field: 'offensiveBonusPhysical' },
  { kind: 'Flat', field: 'offensivePierce' },
  { kind: 'Flat', field: 'offensiveFire' },
  { kind: 'Flat', field: 'offensiveCold' },
  { kind: 'Flat', field: 'offensiveLightning' },
  { kind: 'Flat', field: 'offensivePoison' },
  { kind: 'Flat', field: 'offensiveLife' },
  { kind: 'Flat', field: 'offensiveAether' },
  { kind: 'Flat', field: 'offensiveChaos' },
  { kind: 'Flat', field: 'offensiveElemental' },
  // SlowFlat: 11 fields
  { kind: 'SlowFlat', field: 'offensiveSlowPhysical' },
  { kind: 'SlowFlat', field: 'offensiveSlowBleeding' },
  { kind: 'SlowFlat', field: 'offensiveSlowFire' },
  { kind: 'SlowFlat', field: 'offensiveSlowCold' },
  { kind: 'SlowFlat', field: 'offensiveSlowLightning' },
  { kind: 'SlowFlat', field: 'offensiveSlowPoison' },
  { kind: 'SlowFlat', field: 'offensiveSlowLife' },
  { kind: 'SlowFlat', field: 'offensiveSlowAether' },
  { kind: 'SlowFlat', field: 'offensiveSlowChaos' },
  { kind: 'SlowFlat', field: 'offensiveSlowLifeLeach' },
  { kind: 'SlowFlat', field: 'offensiveSlowManaLeach' },
  // Dmg: 28 fields
  { kind: 'Dmg', field: 'offensiveTotalDamageModifier' },
  { kind: 'Dmg', field: 'offensiveCritDamageModifier' },
  { kind: 'Dmg', field: 'offensivePhysicalModifier' },
  { kind: 'Dmg', field: 'offensivePierceModifier' },
  { kind: 'Dmg', field: 'offensiveFireModifier' },
  { kind: 'Dmg', field: 'offensiveColdModifier' },
  { kind: 'Dmg', field: 'offensiveLightningModifier' },
  { kind: 'Dmg', field: 'offensivePoisonModifier' },
  { kind: 'Dmg', field: 'offensiveLifeModifier' },
  { kind: 'Dmg', field: 'offensiveAetherModifier' },
  { kind: 'Dmg', field: 'offensiveChaosModifier' },
  { kind: 'Dmg', field: 'offensiveElementalModifier' },
  { kind: 'Dmg', field: 'offensiveSlowPhysicalModifier' },
  { kind: 'Dmg', field: 'offensiveSlowPhysicalDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowBleedingModifier' },
  { kind: 'Dmg', field: 'offensiveSlowBleedingDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowFireModifier' },
  { kind: 'Dmg', field: 'offensiveSlowFireDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowColdModifier' },
  { kind: 'Dmg', field: 'offensiveSlowColdDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowLightningModifier' },
  { kind: 'Dmg', field: 'offensiveSlowLightningDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowPoisonModifier' },
  { kind: 'Dmg', field: 'offensiveSlowPoisonDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowLifeModifier' },
  { kind: 'Dmg', field: 'offensiveSlowLifeDurationModifier' },
  { kind: 'Dmg', field: 'offensiveSlowAetherModifier' },
  { kind: 'Dmg', field: 'offensiveSlowChaosModifier' },
  // Leech: 1 fields
  { kind: 'Leech', field: 'offensiveLifeLeech' },
  // OffReflex: 5 fields
  { kind: 'OffReflex', field: 'offensiveStun' },
  { kind: 'OffReflex', field: 'offensiveKnockdown' },
  { kind: 'OffReflex', field: 'offensiveSleep' },
  { kind: 'OffReflex', field: 'offensiveFreeze' },
  { kind: 'OffReflex', field: 'offensivePetrify' },
  // OffSlow: 6 fields
  { kind: 'OffSlow', field: 'offensiveSlowTotalSpeed' },
  { kind: 'OffSlow', field: 'offensiveSlowAttackSpeed' },
  { kind: 'OffSlow', field: 'offensiveSlowSpellCastSpeed' },
  { kind: 'OffSlow', field: 'offensiveSlowRunSpeed' },
  { kind: 'OffSlow', field: 'offensiveSlowOffensiveAbility' },
  { kind: 'OffSlow', field: 'offensiveSlowDefensiveAbility' },
  // OffReduc: 10 fields
  { kind: 'OffReduc', field: 'offensivePhysicalReductionPercent' },
  { kind: 'OffReduc', field: 'offensiveElementalReductionPercent' },
  { kind: 'OffReduc', field: 'offensiveTotalDamageReductionPercent' },
  { kind: 'OffReduc', field: 'offensiveTotalDamageReductionAbsolute' },
  { kind: 'OffReduc', field: 'offensiveTotalResistanceReductionPercent' },
  { kind: 'OffReduc', field: 'offensiveTotalResistanceReductionAbsolute' },
  { kind: 'OffReduc', field: 'offensivePhysicalResistanceReductionPercent' },
  { kind: 'OffReduc', field: 'offensivePhysicalResistanceReductionAbsolute' },
  { kind: 'OffReduc', field: 'offensiveElementalResistanceReductionPercent' },
  { kind: 'OffReduc', field: 'offensiveElementalResistanceReductionAbsolute' },
  // RetalFlat: 10 fields
  { kind: 'RetalFlat', field: 'retaliationPhysical' },
  { kind: 'RetalFlat', field: 'retaliationPierce' },
  { kind: 'RetalFlat', field: 'retaliationFire' },
  { kind: 'RetalFlat', field: 'retaliationCold' },
  { kind: 'RetalFlat', field: 'retaliationLightning' },
  { kind: 'RetalFlat', field: 'retaliationPoison' },
  { kind: 'RetalFlat', field: 'retaliationLife' },
  { kind: 'RetalFlat', field: 'retaliationAether' },
  { kind: 'RetalFlat', field: 'retaliationChaos' },
  { kind: 'RetalFlat', field: 'retaliationElemental' },
  // RetalDur: 12 fields
  { kind: 'RetalDur', field: 'retaliationSlowPhysical' },
  { kind: 'RetalDur', field: 'retaliationSlowPierce' },
  { kind: 'RetalDur', field: 'retaliationSlowFire' },
  { kind: 'RetalDur', field: 'retaliationSlowCold' },
  { kind: 'RetalDur', field: 'retaliationSlowLightning' },
  { kind: 'RetalDur', field: 'retaliationSlowPoison' },
  { kind: 'RetalDur', field: 'retaliationSlowLife' },
  { kind: 'RetalDur', field: 'retaliationSlowAether' },
  { kind: 'RetalDur', field: 'retaliationSlowChaos' },
  { kind: 'RetalDur', field: 'retaliationSlowBleeding' },
  { kind: 'RetalDur', field: 'retaliationSlowAttackSpeed' },
  { kind: 'RetalDur', field: 'retaliationSlowRunSpeed' },
  // RetalMod: 12 fields
  { kind: 'RetalMod', field: 'retaliationTotalDamageModifier' },
  { kind: 'RetalMod', field: 'retaliationPhysicalModifier' },
  { kind: 'RetalMod', field: 'retaliationPierceModifier' },
  { kind: 'RetalMod', field: 'retaliationFireModifier' },
  { kind: 'RetalMod', field: 'retaliationColdModifier' },
  { kind: 'RetalMod', field: 'retaliationLightningModifier' },
  { kind: 'RetalMod', field: 'retaliationPoisonModifier' },
  { kind: 'RetalMod', field: 'retaliationLifeModifier' },
  { kind: 'RetalMod', field: 'retaliationAetherModifier' },
  { kind: 'RetalMod', field: 'retaliationChaosModifier' },
  { kind: 'RetalMod', field: 'retaliationElementalModifier' },
  { kind: 'RetalMod', field: 'retaliationDamageMultModifier' },
  // RetalReflex: 3 fields
  { kind: 'RetalReflex', field: 'retaliationStun' },
  { kind: 'RetalReflex', field: 'retaliationFreeze' },
  { kind: 'RetalReflex', field: 'retaliationConfusion' },
  // Def: 74 fields
  { kind: 'Def', field: 'defensiveBlockModifier' },
  { kind: 'Def', field: 'defensiveBlockAmountModifier' },
  { kind: 'Def', field: 'defensiveProtectionModifier' },
  { kind: 'Def', field: 'defensiveAbsorptionModifier' },
  { kind: 'Def', field: 'defensivePhysical' },
  { kind: 'Def', field: 'defensivePierce' },
  { kind: 'Def', field: 'defensiveFire' },
  { kind: 'Def', field: 'defensiveCold' },
  { kind: 'Def', field: 'defensiveLightning' },
  { kind: 'Def', field: 'defensivePoison' },
  { kind: 'Def', field: 'defensiveLife' },
  { kind: 'Def', field: 'defensiveAether' },
  { kind: 'Def', field: 'defensiveChaos' },
  { kind: 'Def', field: 'defensiveElementalResistance' },
  { kind: 'Def', field: 'defensiveBleeding' },
  { kind: 'Def', field: 'defensiveSlowLifeLeach' },
  { kind: 'Def', field: 'defensiveSlowManaLeach' },
  { kind: 'Def', field: 'defensiveManaBurn' },
  { kind: 'Def', field: 'defensiveAllResistance' },
  { kind: 'Def', field: 'defensivePhysicalModifier' },
  { kind: 'Def', field: 'defensivePierceModifier' },
  { kind: 'Def', field: 'defensiveFireModifier' },
  { kind: 'Def', field: 'defensiveColdModifier' },
  { kind: 'Def', field: 'defensiveLightningModifier' },
  { kind: 'Def', field: 'defensivePoisonModifier' },
  { kind: 'Def', field: 'defensiveLifeModifier' },
  { kind: 'Def', field: 'defensiveAetherModifier' },
  { kind: 'Def', field: 'defensiveChaosModifier' },
  { kind: 'Def', field: 'defensiveElementalModifier' },
  { kind: 'Def', field: 'defensiveBleedingModifier' },
  { kind: 'Def', field: 'defensiveSlowLifeLeachModifier' },
  { kind: 'Def', field: 'defensiveSlowManaLeachModifier' },
  { kind: 'Def', field: 'defensivePhysicalDuration' },
  { kind: 'Def', field: 'defensiveFireDuration' },
  { kind: 'Def', field: 'defensiveColdDuration' },
  { kind: 'Def', field: 'defensiveLightningDuration' },
  { kind: 'Def', field: 'defensivePoisonDuration' },
  { kind: 'Def', field: 'defensiveLifeDuration' },
  { kind: 'Def', field: 'defensiveAetherDuration' },
  { kind: 'Def', field: 'defensiveChaosDuration' },
  { kind: 'Def', field: 'defensiveBleedingDuration' },
  { kind: 'Def', field: 'defensiveSlowLifeLeachDuration' },
  { kind: 'Def', field: 'defensiveSlowManaLeachDuration' },
  { kind: 'Def', field: 'defensivePhysicalDurationModifier' },
  { kind: 'Def', field: 'defensiveFireDurationModifier' },
  { kind: 'Def', field: 'defensiveColdDurationModifier' },
  { kind: 'Def', field: 'defensiveLightningDurationModifier' },
  { kind: 'Def', field: 'defensivePoisonDurationModifier' },
  { kind: 'Def', field: 'defensiveLifeDurationModifier' },
  { kind: 'Def', field: 'defensiveAetherDurationModifier' },
  { kind: 'Def', field: 'defensiveChaosDurationModifier' },
  { kind: 'Def', field: 'defensiveBleedingDurationModifier' },
  { kind: 'Def', field: 'defensiveSlowLifeLeachDurationModifier' },
  { kind: 'Def', field: 'defensiveSlowManaLeachDurationModifier' },
  { kind: 'Def', field: 'defensiveDisruption' },
  { kind: 'Def', field: 'defensiveStun' },
  { kind: 'Def', field: 'defensiveStunModifier' },
  { kind: 'Def', field: 'defensiveFreeze' },
  { kind: 'Def', field: 'defensiveTrap' },
  { kind: 'Def', field: 'defensivePetrify' },
  { kind: 'Def', field: 'defensiveSleep' },
  { kind: 'Def', field: 'defensiveSleepModifier' },
  { kind: 'Def', field: 'defensiveKnockdown' },
  { kind: 'Def', field: 'defensiveKnockdownModifier' },
  { kind: 'Def', field: 'defensiveTaunt' },
  { kind: 'Def', field: 'defensiveFear' },
  { kind: 'Def', field: 'defensiveConfusion' },
  { kind: 'Def', field: 'defensiveConvert' },
  { kind: 'Def', field: 'defensiveTotalSpeedResistance' },
  { kind: 'Def', field: 'defensiveCrowdControl' },
  { kind: 'Def', field: 'defensiveReflect' },
  { kind: 'Def', field: 'defensiveReflectModifier' },
  { kind: 'Def', field: 'defensivePercentCurrentLife' },
  { kind: 'Def', field: 'defensivePercentReflectionResistance' },
  // Conv: 2 fields
  { kind: 'Conv', field: 'conversionPercentage' },
  { kind: 'Conv', field: 'conversionPercentage2' },
  // Skill: 6 fields
  { kind: 'Skill', field: 'skillCooldownReduction' },
  { kind: 'Skill', field: 'skillManaCostReduction' },
  { kind: 'Skill', field: 'skillComboChargeSpendReduction' },
  { kind: 'Skill', field: 'skillProjectileSpeedModifier' },
  { kind: 'Skill', field: 'skillCooldownReductionModifier' },
  { kind: 'Skill', field: 'skillManaCostReductionModifier' },
];
